//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepeatingWords {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RepeatingWords.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a backup.
        /// </summary>
        public static string BackUpCreateBtn {
            get {
                return ResourceManager.GetString("BackUpCreateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save backup in the local memory.
        /// </summary>
        public static string BackUpCreateLocal {
            get {
                return ResourceManager.GetString("BackUpCreateLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while creating the backup.
        /// </summary>
        public static string BackUpErrorCreated {
            get {
                return ResourceManager.GetString("BackUpErrorCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred, the backup is not restored.
        /// </summary>
        public static string BackUpErrorRestored {
            get {
                return ResourceManager.GetString("BackUpErrorRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save backup in Google Drive.
        /// </summary>
        public static string BackUpGoogleDrive {
            get {
                return ResourceManager.GetString("BackUpGoogleDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the local memory.
        /// </summary>
        public static string BackUpInLocal {
            get {
                return ResourceManager.GetString("BackUpInLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup method.
        /// </summary>
        public static string BackupMethod {
            get {
                return ResourceManager.GetString("BackupMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Google Drive.
        /// </summary>
        public static string BackUpOnGoogle {
            get {
                return ResourceManager.GetString("BackUpOnGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore a backup.
        /// </summary>
        public static string BackUpRestoreBtn {
            get {
                return ResourceManager.GetString("BackUpRestoreBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup restored.
        /// </summary>
        public static string BackupRestored {
            get {
                return ResourceManager.GetString("BackupRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search a backup.
        /// </summary>
        public static string BackUpSearch {
            get {
                return ResourceManager.GetString("BackUpSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string BackupStr {
            get {
                return ResourceManager.GetString("BackupStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The backup was created successfully.
        /// </summary>
        public static string BackupWasCreatedGoogle {
            get {
                return ResourceManager.GetString("BackupWasCreatedGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The backup was created in the directory.
        /// </summary>
        public static string BackupWasCreatedInFolder {
            get {
                return ResourceManager.GetString("BackupWasCreatedInFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About app.
        /// </summary>
        public static string ButtonAbout {
            get {
                return ResourceManager.GetString("ButtonAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create dictionary.
        /// </summary>
        public static string ButtonAddDict {
            get {
                return ResourceManager.GetString("ButtonAddDict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionaries.
        /// </summary>
        public static string ButtonAddDictionaryOrWords {
            get {
                return ResourceManager.GetString("ButtonAddDictionaryOrWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create word.
        /// </summary>
        public static string ButtonAddWord {
            get {
                return ResourceManager.GetString("ButtonAddWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import words from the file.
        /// </summary>
        public static string ButtonAddWorFrFile {
            get {
                return ResourceManager.GetString("ButtonAddWorFrFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add dictionary from the server.
        /// </summary>
        public static string ButtonAddWorFrNet {
            get {
                return ResourceManager.GetString("ButtonAddWorFrNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string ButtonCreate {
            get {
                return ResourceManager.GetString("ButtonCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create the dictionary.
        /// </summary>
        public static string ButtonHowCreateDictAndaddWord {
            get {
                return ResourceManager.GetString("ButtonHowCreateDictAndaddWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import words from the file.
        /// </summary>
        public static string ButtonHowIportFile {
            get {
                return ResourceManager.GetString("ButtonHowIportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string ButtonImport {
            get {
                return ResourceManager.GetString("ButtonImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next card.
        /// </summary>
        public static string ButtonNextWord {
            get {
                return ResourceManager.GetString("ButtonNextWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string ButtonPolicy {
            get {
                return ResourceManager.GetString("ButtonPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the dictionary.
        /// </summary>
        public static string ButtonRemove {
            get {
                return ResourceManager.GetString("ButtonRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studying of words.
        /// </summary>
        public static string ButtonRepeatWords {
            get {
                return ResourceManager.GetString("ButtonRepeatWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a review.
        /// </summary>
        public static string ButtonReviewText {
            get {
                return ResourceManager.GetString("ButtonReviewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave a comment.
        /// </summary>
        public static string ButtonSendReview {
            get {
                return ResourceManager.GetString("ButtonSendReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the list of words.
        /// </summary>
        public static string ButtonShowWords {
            get {
                return ResourceManager.GetString("ButtonShowWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn the card.
        /// </summary>
        public static string ButtonTurnCard {
            get {
                return ResourceManager.GetString("ButtonTurnCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learning.
        /// </summary>
        public static string ChooseDictionaryForRepeat {
            get {
                return ResourceManager.GetString("ChooseDictionaryForRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the dictionary name.
        /// </summary>
        public static string EntryNameDict {
            get {
                return ResourceManager.GetString("EntryNameDict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use these cards of words for a learning of foreign language.
        /// </summary>
        public static string HeaderMain {
            get {
                return ResourceManager.GetString("HeaderMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string HowUseApp {
            get {
                return ResourceManager.GetString("HowUseApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the dictionary.
        /// </summary>
        public static string LabelChooseDict {
            get {
                return ResourceManager.GetString("LabelChooseDict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select or create  dictionary.
        /// </summary>
        public static string LabelChooseDictOrCreate {
            get {
                return ResourceManager.GetString("LabelChooseDictOrCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the file to import.
        /// </summary>
        public static string LabelChooseFile {
            get {
                return ResourceManager.GetString("LabelChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggest keyboard for transcription.
        /// </summary>
        public static string LabelChooseShowKeyboardTrans {
            get {
                return ResourceManager.GetString("LabelChooseShowKeyboardTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose theme.
        /// </summary>
        public static string LabelChooseTheme {
            get {
                return ResourceManager.GetString("LabelChooseTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turned:.
        /// </summary>
        public static string LabelCountTurned {
            get {
                return ResourceManager.GetString("LabelCountTurned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the dictionary for load into the phone.
        /// </summary>
        public static string LabelDictionaryListFromNet {
            get {
                return ResourceManager.GetString("LabelDictionaryListFromNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ivan Kuzmuk.
        /// </summary>
        public static string LabelFIO {
            get {
                return ResourceManager.GetString("LabelFIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrer the first word.
        /// </summary>
        public static string LabelFirstWord {
            get {
                return ResourceManager.GetString("LabelFirstWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To get started with the application, you need:
        ///Add your dictionary with words and add words individually, add a dictionary from the Internet by selecting the language you want, or add words to the dictionary from the file..
        /// </summary>
        public static string LabelForStart {
            get {
                return ResourceManager.GetString("LabelForStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add words from file.
        /// </summary>
        public static string LabelHeadAddFile {
            get {
                return ResourceManager.GetString("LabelHeadAddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create the dictionary and add the word.
        /// </summary>
        public static string LabelHeadCreateInstr {
            get {
                return ResourceManager.GetString("LabelHeadCreateInstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions of the app.
        /// </summary>
        public static string LabelInstruction {
            get {
                return ResourceManager.GetString("LabelInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose language.
        /// </summary>
        public static string LabelLanguageListFromNet {
            get {
                return ResourceManager.GetString("LabelLanguageListFromNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the dictionary name.
        /// </summary>
        public static string LabelNameDict {
            get {
                return ResourceManager.GetString("LabelNameDict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need for import words from the file: .
        /// </summary>
        public static string LabelNeedAddFile {
            get {
                return ResourceManager.GetString("LabelNeedAddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Notepad.exe create the file with &quot;.txt&quot; format on the computer .
        /// </summary>
        public static string LabelNeedCreate {
            get {
                return ResourceManager.GetString("LabelNeedCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to file:.
        /// </summary>
        public static string LabelPathToRoot {
            get {
                return ResourceManager.GetString("LabelPathToRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved..
        /// </summary>
        public static string LabelRights {
            get {
                return ResourceManager.GetString("LabelRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To add your dictionary, click [DICTIONARIES].
        /// </summary>
        public static string LabelScreen1 {
            get {
                return ResourceManager.GetString("LabelScreen1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can also change the word or delete it by calling the context menu by clicking on the word.
        /// </summary>
        public static string LabelScreen10 {
            get {
                return ResourceManager.GetString("LabelScreen10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the [STUDING OF WORDS] button will open the context menu for selecting the learning language.
        /// </summary>
        public static string LabelScreen11 {
            get {
                return ResourceManager.GetString("LabelScreen11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After selecting the language, a study window appears, where the figures show: the total number of words / words displayed / inverted words.
        /// </summary>
        public static string LabelScreen12 {
            get {
                return ResourceManager.GetString("LabelScreen12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then click [CREATE DICTIONARY].
        /// </summary>
        public static string LabelScreen2 {
            get {
                return ResourceManager.GetString("LabelScreen2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill the file as in example:  word  [transcription] translate. You have to use [ ] in every line..
        /// </summary>
        public static string LabelScreen21 {
            get {
                return ResourceManager.GetString("LabelScreen21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to save file in UTF-8..
        /// </summary>
        public static string LabelScreen22 {
            get {
                return ResourceManager.GetString("LabelScreen22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load this file into the phone..
        /// </summary>
        public static string LabelScreen231 {
            get {
                return ResourceManager.GetString("LabelScreen231", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select dictionary and select  [Import words from the file] in context menu.
        /// </summary>
        public static string LabelScreen232 {
            get {
                return ResourceManager.GetString("LabelScreen232", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find and select file on smartphone. Wait while import words will be complete..
        /// </summary>
        public static string LabelScreen24 {
            get {
                return ResourceManager.GetString("LabelScreen24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After that shows the list of words..
        /// </summary>
        public static string LabelScreen25 {
            get {
                return ResourceManager.GetString("LabelScreen25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of the dictionary and click the [CREATE].
        /// </summary>
        public static string LabelScreen3 {
            get {
                return ResourceManager.GetString("LabelScreen3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the created dictionary.
        /// </summary>
        public static string LabelScreen4 {
            get {
                return ResourceManager.GetString("LabelScreen4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select [Create word].
        /// </summary>
        public static string LabelScreen5 {
            get {
                return ResourceManager.GetString("LabelScreen5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the word, translate of the word and transcription.Click [Create word].
        /// </summary>
        public static string LabelScreen6 {
            get {
                return ResourceManager.GetString("LabelScreen6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you click on the transcription input field, you can select a keyboard
        ///smartphone or keyboard transcription.
        /// </summary>
        public static string LabelScreen7 {
            get {
                return ResourceManager.GetString("LabelScreen7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After adding words click on the created dictionary and select [View the list of words].
        /// </summary>
        public static string LabelScreen8 {
            get {
                return ResourceManager.GetString("LabelScreen8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where you can also add words (1), go to the study of words (2).
        /// </summary>
        public static string LabelScreen9 {
            get {
                return ResourceManager.GetString("LabelScreen9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the translation of the word.
        /// </summary>
        public static string LabelSecondWord {
            get {
                return ResourceManager.GetString("LabelSecondWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string LabelSettings {
            get {
                return ResourceManager.GetString("LabelSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggest.
        /// </summary>
        public static string LabelShowKeyboard {
            get {
                return ResourceManager.GetString("LabelShowKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string LabelThemeDark {
            get {
                return ResourceManager.GetString("LabelThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string LabelThemeLight {
            get {
                return ResourceManager.GetString("LabelThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the transcription of the word.
        /// </summary>
        public static string LabelTranscription {
            get {
                return ResourceManager.GetString("LabelTranscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please leave the comment about application, your judgement is very important for us..
        /// </summary>
        public static string MessagePleaseReview {
            get {
                return ResourceManager.GetString("MessagePleaseReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ModalActCancel {
            get {
                return ResourceManager.GetString("ModalActCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string ModalActChange {
            get {
                return ResourceManager.GetString("ModalActChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the keyboard:.
        /// </summary>
        public static string ModalActChooseKeyboard {
            get {
                return ResourceManager.GetString("ModalActChooseKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From the first language.
        /// </summary>
        public static string ModalActFromFtoTr {
            get {
                return ResourceManager.GetString("ModalActFromFtoTr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is a foreign word display first?.
        /// </summary>
        public static string ModalActFromTrtoF {
            get {
                return ResourceManager.GetString("ModalActFromTrtoF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of words.
        /// </summary>
        public static string ModalActList {
            get {
                return ResourceManager.GetString("ModalActList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System keyboard.
        /// </summary>
        public static string ModalActSysKeyboard {
            get {
                return ResourceManager.GetString("ModalActSysKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcription keyboard.
        /// </summary>
        public static string ModalActTranscKeyboard {
            get {
                return ResourceManager.GetString("ModalActTranscKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The words are added..
        /// </summary>
        public static string ModalAddWords {
            get {
                return ResourceManager.GetString("ModalAddWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All words are passed.
        /// </summary>
        public static string ModalAllWordsComplete {
            get {
                return ResourceManager.GetString("ModalAllWordsComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check internet connection.
        /// </summary>
        public static string ModalCheckNet {
            get {
                return ResourceManager.GetString("ModalCheckNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the action:.
        /// </summary>
        public static string ModalChooceAction {
            get {
                return ResourceManager.GetString("ModalChooceAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select display language:.
        /// </summary>
        public static string ModalChooseLang {
            get {
                return ResourceManager.GetString("ModalChooseLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dictionary.
        /// </summary>
        public static string ModalDict {
            get {
                return ResourceManager.GetString("ModalDict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dictionary or word was deleted!.
        /// </summary>
        public static string ModalDictOrWordRemove {
            get {
                return ResourceManager.GetString("ModalDictOrWordRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        public static string ModalException {
            get {
                return ResourceManager.GetString("ModalException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string ModalFinish {
            get {
                return ResourceManager.GetString("ModalFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Words aren&apos;t added to the dictionary, perhaps incorrect file..
        /// </summary>
        public static string ModalIncorrectFile {
            get {
                return ResourceManager.GetString("ModalIncorrectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studying of unlearned words.
        /// </summary>
        public static string ModalLerningTurnedWords {
            get {
                return ResourceManager.GetString("ModalLerningTurnedWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dictionary doesn&apos;t have words..
        /// </summary>
        public static string ModalNoWord {
            get {
                return ResourceManager.GetString("ModalNoWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is deleted..
        /// </summary>
        public static string ModalRemove {
            get {
                return ResourceManager.GetString("ModalRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ModalRemoveAct {
            get {
                return ResourceManager.GetString("ModalRemoveAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string ModalRestart {
            get {
                return ResourceManager.GetString("ModalRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The word.
        /// </summary>
        public static string ModalWord {
            get {
                return ResourceManager.GetString("ModalWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is deleted..
        /// </summary>
        public static string ModalWordRemove {
            get {
                return ResourceManager.GetString("ModalWordRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For adding of the word fill all fields (except a transcription)..
        /// </summary>
        public static string ModelForAddingWord {
            get {
                return ResourceManager.GetString("ModelForAddingWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all fields are filled.
        /// </summary>
        public static string ModelNoFillFull {
            get {
                return ResourceManager.GetString("ModelNoFillFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter name of the dictionary.
        /// </summary>
        public static string ModelNoFillFullNameDictionary {
            get {
                return ResourceManager.GetString("ModelNoFillFullNameDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The word is added!.
        /// </summary>
        public static string ModelWordAdd {
            get {
                return ResourceManager.GetString("ModelWordAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The word is changed!.
        /// </summary>
        public static string ModelWordChange {
            get {
                return ResourceManager.GetString("ModelWordChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - not learned words.
        /// </summary>
        public static string NotLearningPostfics {
            get {
                return ResourceManager.GetString("NotLearningPostfics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice language.
        /// </summary>
        public static string PickerText {
            get {
                return ResourceManager.GetString("PickerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to screen1.jpg.
        /// </summary>
        public static string screen1 {
            get {
                return ResourceManager.GetString("screen1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to screen10.jpg.
        /// </summary>
        public static string screen10 {
            get {
                return ResourceManager.GetString("screen10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to screen11.jpg.
        /// </summary>
        public static string screen11 {
            get {
                return ResourceManager.GetString("screen11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to screen12.jpg.
        /// </summary>
        public static string screen12 {
            get {
                return ResourceManager.GetString("screen12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to screen2.jpg.
        /// </summary>
        public static string screen2 {
            get {
                return ResourceManager.GetString("screen2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to screen20.jpg.
        /// </summary>
        public static string screen20 {
            get {
                return ResourceManager.GetString("screen20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to screen21.jpg.
        /// </summary>
        public static string screen21 {
            get {
                return ResourceManager.GetString("screen21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to screen22.jpg.
        /// </summary>
        public static string screen22 {
            get {
                return ResourceManager.GetString("screen22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to screen23.jpg.
        /// </summary>
        public static string screen23 {
            get {
                return ResourceManager.GetString("screen23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to screen24.jpg.
        /// </summary>
        public static string screen24 {
            get {
                return ResourceManager.GetString("screen24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to screen3.jpg.
        /// </summary>
        public static string screen3 {
            get {
                return ResourceManager.GetString("screen3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to screen4.jpg.
        /// </summary>
        public static string screen4 {
            get {
                return ResourceManager.GetString("screen4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to screen5.jpg.
        /// </summary>
        public static string screen5 {
            get {
                return ResourceManager.GetString("screen5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to screen6.jpg.
        /// </summary>
        public static string screen6 {
            get {
                return ResourceManager.GetString("screen6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to screen7.jpg.
        /// </summary>
        public static string screen7 {
            get {
                return ResourceManager.GetString("screen7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to screen8.jpg.
        /// </summary>
        public static string screen8 {
            get {
                return ResourceManager.GetString("screen8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to screen9.jpg.
        /// </summary>
        public static string screen9 {
            get {
                return ResourceManager.GetString("screen9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string SuccessStr {
            get {
                return ResourceManager.GetString("SuccessStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string TitleAbout {
            get {
                return ResourceManager.GetString("TitleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the word.
        /// </summary>
        public static string TitleChangeWord {
            get {
                return ResourceManager.GetString("TitleChangeWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a word.
        /// </summary>
        public static string TitleCreateWord {
            get {
                return ResourceManager.GetString("TitleCreateWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionaries.
        /// </summary>
        public static string TitleDictionaries {
            get {
                return ResourceManager.GetString("TitleDictionaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File explorer.
        /// </summary>
        public static string TitleExplorer {
            get {
                return ResourceManager.GetString("TitleExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to add words.
        /// </summary>
        public static string TitleHelpAddWord {
            get {
                return ResourceManager.GetString("TitleHelpAddWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string TitleHelpers {
            get {
                return ResourceManager.GetString("TitleHelpers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to import words.
        /// </summary>
        public static string TitleHelpImportFile {
            get {
                return ResourceManager.GetString("TitleHelpImportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string TitleLanguages {
            get {
                return ResourceManager.GetString("TitleLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards of words.
        /// </summary>
        public static string TitleMain {
            get {
                return ResourceManager.GetString("TitleMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string TitleSettings {
            get {
                return ResourceManager.GetString("TitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcription.
        /// </summary>
        public static string TitleTranscription {
            get {
                return ResourceManager.GetString("TitleTranscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
