//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepeatingWords {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RepeatingWords.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All words:.
        /// </summary>
        public static string AllWordsCountLabel {
            get {
                return ResourceManager.GetString("AllWordsCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a backup.
        /// </summary>
        public static string BackUpCreateBtn {
            get {
                return ResourceManager.GetString("BackUpCreateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save backup in the local memory.
        /// </summary>
        public static string BackUpCreateLocal {
            get {
                return ResourceManager.GetString("BackUpCreateLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while creating the backup.
        /// </summary>
        public static string BackUpErrorCreated {
            get {
                return ResourceManager.GetString("BackUpErrorCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred, the backup is not restored.
        /// </summary>
        public static string BackUpErrorRestored {
            get {
                return ResourceManager.GetString("BackUpErrorRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save backup in Google Drive.
        /// </summary>
        public static string BackUpGoogleDrive {
            get {
                return ResourceManager.GetString("BackUpGoogleDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the local memory.
        /// </summary>
        public static string BackUpInLocal {
            get {
                return ResourceManager.GetString("BackUpInLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup method.
        /// </summary>
        public static string BackupMethod {
            get {
                return ResourceManager.GetString("BackupMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Google Drive.
        /// </summary>
        public static string BackUpOnGoogle {
            get {
                return ResourceManager.GetString("BackUpOnGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore a backup.
        /// </summary>
        public static string BackUpRestoreBtn {
            get {
                return ResourceManager.GetString("BackUpRestoreBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup restored.
        /// </summary>
        public static string BackupRestored {
            get {
                return ResourceManager.GetString("BackupRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search a backup.
        /// </summary>
        public static string BackUpSearch {
            get {
                return ResourceManager.GetString("BackUpSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The backup was created successfully.
        /// </summary>
        public static string BackupWasCreatedGoogle {
            get {
                return ResourceManager.GetString("BackupWasCreatedGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The backup was created in the directory.
        /// </summary>
        public static string BackupWasCreatedInFolder {
            get {
                return ResourceManager.GetString("BackupWasCreatedInFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add language.
        /// </summary>
        public static string BtnAddLang {
            get {
                return ResourceManager.GetString("BtnAddLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About app.
        /// </summary>
        public static string ButtonAbout {
            get {
                return ResourceManager.GetString("ButtonAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create dictionary.
        /// </summary>
        public static string ButtonAddDict {
            get {
                return ResourceManager.GetString("ButtonAddDict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionaries.
        /// </summary>
        public static string ButtonAddDictionaryOrWords {
            get {
                return ResourceManager.GetString("ButtonAddDictionaryOrWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to check ✓.
        /// </summary>
        public static string ButtonCheck {
            get {
                return ResourceManager.GetString("ButtonCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string ButtonCreate {
            get {
                return ResourceManager.GetString("ButtonCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hint ?.
        /// </summary>
        public static string ButtonHint {
            get {
                return ResourceManager.GetString("ButtonHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import words from file.
        /// </summary>
        public static string ButtonHowIportFile {
            get {
                return ResourceManager.GetString("ButtonHowIportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from file.
        /// </summary>
        public static string ButtonImport {
            get {
                return ResourceManager.GetString("ButtonImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next card.
        /// </summary>
        public static string ButtonNextWord {
            get {
                return ResourceManager.GetString("ButtonNextWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string ButtonPolicy {
            get {
                return ResourceManager.GetString("ButtonPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the dictionary.
        /// </summary>
        public static string ButtonRemove {
            get {
                return ResourceManager.GetString("ButtonRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the language.
        /// </summary>
        public static string ButtonRemoveLanguage {
            get {
                return ResourceManager.GetString("ButtonRemoveLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studying of words.
        /// </summary>
        public static string ButtonRepeatWords {
            get {
                return ResourceManager.GetString("ButtonRepeatWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave a comment.
        /// </summary>
        public static string ButtonSendReview {
            get {
                return ResourceManager.GetString("ButtonSendReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the list of words.
        /// </summary>
        public static string ButtonShowWords {
            get {
                return ResourceManager.GetString("ButtonShowWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlearned words.
        /// </summary>
        public static string ButtonStudyNotLearning {
            get {
                return ResourceManager.GetString("ButtonStudyNotLearning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top 100 russian words.
        /// </summary>
        public static string DefaultDictionaryName {
            get {
                return ResourceManager.GetString("DefaultDictionaryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My dictionary.
        /// </summary>
        public static string DefaultLanguage {
            get {
                return ResourceManager.GetString("DefaultLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting...
        /// </summary>
        public static string Deleting {
            get {
                return ResourceManager.GetString("Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the answer.
        /// </summary>
        public static string EnterAnswer {
            get {
                return ResourceManager.GetString("EnterAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the dictionary name.
        /// </summary>
        public static string EntryNameDict {
            get {
                return ResourceManager.GetString("EntryNameDict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the language name.
        /// </summary>
        public static string EntryNameLang {
            get {
                return ResourceManager.GetString("EntryNameLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while importing words. May be bad data in file..
        /// </summary>
        public static string ErrorImport {
            get {
                return ResourceManager.GetString("ErrorImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string IsCurrentLang {
            get {
                return ResourceManager.GetString("IsCurrentLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the file to import.
        /// </summary>
        public static string LabelChooseFile {
            get {
                return ResourceManager.GetString("LabelChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First view word on.
        /// </summary>
        public static string LabelChooseFirstLanguage {
            get {
                return ResourceManager.GetString("LabelChooseFirstLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggest keyboard for transcription.
        /// </summary>
        public static string LabelChooseShowKeyboardTrans {
            get {
                return ResourceManager.GetString("LabelChooseShowKeyboardTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose theme.
        /// </summary>
        public static string LabelChooseTheme {
            get {
                return ResourceManager.GetString("LabelChooseTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ivan Kuzmuk.
        /// </summary>
        public static string LabelFIO {
            get {
                return ResourceManager.GetString("LabelFIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign language.
        /// </summary>
        public static string LabelFirstLanguageForeign {
            get {
                return ResourceManager.GetString("LabelFirstLanguageForeign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native language.
        /// </summary>
        public static string LabelFirstLanguageNative {
            get {
                return ResourceManager.GetString("LabelFirstLanguageNative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the native word.
        /// </summary>
        public static string LabelFirstWord {
            get {
                return ResourceManager.GetString("LabelFirstWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create the dictionary and add the word.
        /// </summary>
        public static string LabelHeadCreateInstr {
            get {
                return ResourceManager.GetString("LabelHeadCreateInstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to file:.
        /// </summary>
        public static string LabelPathToRoot {
            get {
                return ResourceManager.GetString("LabelPathToRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved..
        /// </summary>
        public static string LabelRights {
            get {
                return ResourceManager.GetString("LabelRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using Notepad.exe create a file with &quot;.txt&quot; format on the computer. Fill the file as in example:  native word [transcription] translate. You have to use [ ] in every line. If transcription is epsent use: word[] translate.
        /// </summary>
        public static string LabelScreen21 {
            get {
                return ResourceManager.GetString("LabelScreen21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must to save file in UTF-8..
        /// </summary>
        public static string LabelScreen22 {
            get {
                return ResourceManager.GetString("LabelScreen22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load this file into the phone or Google Drive.
        /// </summary>
        public static string LabelScreen231 {
            get {
                return ResourceManager.GetString("LabelScreen231", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option 1. Select [Import from file] in the language context menu.
        /// </summary>
        public static string LabelScreen232 {
            get {
                return ResourceManager.GetString("LabelScreen232", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a name for the new dictionary and click [Create].
        /// </summary>
        public static string LabelScreen233 {
            get {
                return ResourceManager.GetString("LabelScreen233", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option 2. Select [View Word List] in the dictionary context menu.
        /// </summary>
        public static string LabelScreen234 {
            get {
                return ResourceManager.GetString("LabelScreen234", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the [Import from file] button.
        /// </summary>
        public static string LabelScreen235 {
            get {
                return ResourceManager.GetString("LabelScreen235", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A standard file manager will open, select your file and click on it. Words will be imported from the file into the dictionary..
        /// </summary>
        public static string LabelScreen25 {
            get {
                return ResourceManager.GetString("LabelScreen25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the translation of the word.
        /// </summary>
        public static string LabelSecondWord {
            get {
                return ResourceManager.GetString("LabelSecondWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggest.
        /// </summary>
        public static string LabelShowKeyboard {
            get {
                return ResourceManager.GetString("LabelShowKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string LabelThemeDark {
            get {
                return ResourceManager.GetString("LabelThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the transcription of the word.
        /// </summary>
        public static string LabelTranscription {
            get {
                return ResourceManager.GetString("LabelTranscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please leave the comment about application, your judgement is very important for us..
        /// </summary>
        public static string MessagePleaseReview {
            get {
                return ResourceManager.GetString("MessagePleaseReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ModalActCancel {
            get {
                return ResourceManager.GetString("ModalActCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string ModalActChange {
            get {
                return ResourceManager.GetString("ModalActChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is foreign words display first?.
        /// </summary>
        public static string ModalActFromTrtoF {
            get {
                return ResourceManager.GetString("ModalActFromTrtoF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The words are added..
        /// </summary>
        public static string ModalAddWords {
            get {
                return ResourceManager.GetString("ModalAddWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check internet connection.
        /// </summary>
        public static string ModalCheckNet {
            get {
                return ResourceManager.GetString("ModalCheckNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dictionary.
        /// </summary>
        public static string ModalDict {
            get {
                return ResourceManager.GetString("ModalDict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        public static string ModalException {
            get {
                return ResourceManager.GetString("ModalException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! You looked at all the words..
        /// </summary>
        public static string ModalFinishWords {
            get {
                return ResourceManager.GetString("ModalFinishWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ModalRemoveAct {
            get {
                return ResourceManager.GetString("ModalRemoveAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of the application is available.Do you want to upgrade app?.
        /// </summary>
        public static string ModalUpdateApp {
            get {
                return ResourceManager.GetString("ModalUpdateApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For adding of the word fill all fields (except a transcription)..
        /// </summary>
        public static string ModelForAddingWord {
            get {
                return ResourceManager.GetString("ModelForAddingWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all fields are filled.
        /// </summary>
        public static string ModelNoFillFull {
            get {
                return ResourceManager.GetString("ModelNoFillFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The word is added!.
        /// </summary>
        public static string ModelWordAdd {
            get {
                return ResourceManager.GetString("ModelWordAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The word is changed!.
        /// </summary>
        public static string ModelWordChange {
            get {
                return ResourceManager.GetString("ModelWordChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - not learned words.
        /// </summary>
        public static string NotLearningPostfics {
            get {
                return ResourceManager.GetString("NotLearningPostfics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlearned:.
        /// </summary>
        public static string OpenedWordsCountLabel {
            get {
                return ResourceManager.GetString("OpenedWordsCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice language.
        /// </summary>
        public static string PickerText {
            get {
                return ResourceManager.GetString("PickerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving state...
        /// </summary>
        public static string SaveState {
            get {
                return ResourceManager.GetString("SaveState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to picture1en.png.
        /// </summary>
        public static string screen1 {
            get {
                return ResourceManager.GetString("screen1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to picture2en.png.
        /// </summary>
        public static string screen2 {
            get {
                return ResourceManager.GetString("screen2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to screen20.jpg.
        /// </summary>
        public static string screen20 {
            get {
                return ResourceManager.GetString("screen20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to screen21.jpg.
        /// </summary>
        public static string screen21 {
            get {
                return ResourceManager.GetString("screen21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to screen25.png.
        /// </summary>
        public static string screen25 {
            get {
                return ResourceManager.GetString("screen25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to picture3en.png.
        /// </summary>
        public static string screen3 {
            get {
                return ResourceManager.GetString("screen3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to picture4en.png.
        /// </summary>
        public static string screen4 {
            get {
                return ResourceManager.GetString("screen4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learned:.
        /// </summary>
        public static string ShowedWordsCountLabel {
            get {
                return ResourceManager.GetString("ShowedWordsCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string SuccessStr {
            get {
                return ResourceManager.GetString("SuccessStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string TitleAbout {
            get {
                return ResourceManager.GetString("TitleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the word.
        /// </summary>
        public static string TitleChangeWord {
            get {
                return ResourceManager.GetString("TitleChangeWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a word.
        /// </summary>
        public static string TitleCreateWord {
            get {
                return ResourceManager.GetString("TitleCreateWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionaries.
        /// </summary>
        public static string TitleDictionaries {
            get {
                return ResourceManager.GetString("TitleDictionaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File explorer.
        /// </summary>
        public static string TitleExplorer {
            get {
                return ResourceManager.GetString("TitleExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string TitleHelpers {
            get {
                return ResourceManager.GetString("TitleHelpers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import words from file.
        /// </summary>
        public static string TitleHelpImportFile {
            get {
                return ResourceManager.GetString("TitleHelpImportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string TitleLanguages {
            get {
                return ResourceManager.GetString("TitleLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards of words.
        /// </summary>
        public static string TitleMain {
            get {
                return ResourceManager.GetString("TitleMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string TitleSettings {
            get {
                return ResourceManager.GetString("TitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcription.
        /// </summary>
        public static string TitleTranscription {
            get {
                return ResourceManager.GetString("TitleTranscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a voice language.
        /// </summary>
        public static string TitleVolumeLanguages {
            get {
                return ResourceManager.GetString("TitleVolumeLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading...
        /// </summary>
        public static string WaitIndicator {
            get {
                return ResourceManager.GetString("WaitIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dictionary is empty.
        /// </summary>
        public static string WordsListIsEmpty {
            get {
                return ResourceManager.GetString("WordsListIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
